title: Michael J. Bernstein
lang: en

nav:
  - url: /about.html
    label: About
  - url: /focus.html
    label: Focus Areas
  - url: /capacity.html
    label: Capacity Building
  - url: /leadership.html
    label: Leadership
  - url: /contact.html
    label: Contact
